- hosts: localhost
  connection: local
  become: yes
  vars:
    local_home: "{{ lookup('env','HOME') }}"
  tasks:
    - debug:
        msg: "{{ local_home }}"
    - name: install modules for RedHat
      yum: >
        name={{ item }}
        state=present
      with_items:
        - zsh
        - git
        - vim
        - tig
        - wget
        - docker
        - neovim
        - bzip2-devel
        - readline-devel
        - sqlite-devel
      when: "ansible_os_family == 'RedHat'"

    - name: install modules for Debian
      apt: >
        name={{ item }}
        state=present
      with_items:
        - zsh
        - git
        - vim
        - tig
        - wget
        - docker
        - neovim
        - bzip2-devel
        - readline-devel
        - sqlite-devel
      when: "ansible_os_family == 'Debian'"

    - name: install modules for MacOS
      homebrew: >
        name={{ item }}
        state=present
      with_items:
        - zsh
        - git
        - vim
        - tig
        - wget
        - docker
        - neovim
      when: "ansible_os_family == 'Darwin'"
      become: no

    - name: make directory
      file: >
        path=/etc/profile.d
        state=directory
        
    - name: edit zprofile
      copy:
        dest: "{{ local_home }}/.zprofile"
        content: |
          for i in /etc/profile.d/*.sh ; do
            [ -r $i ] && source $i
          done

    - name: which zsh
      shell: which zsh
      register: zsh_path
      changed_when: False

    - name: change default shell
      user: >
        name={{ ansible_env.USER }}
        shell={{ zsh_path.stdout }}

    - name: make directory
      file: >
        path={{ local_home }}/git/rusagedougawa/dotfiles
        owner={{ ansible_env.USER }}
        state=directory
        recurse=yes

    - name: install dotfiles
      git: >
        repo=https://github.com/rusagedougawa/dotfiles.git
        dest={{ local_home }}/git/rusagedougawa/dotfiles

    - name: link dotfiles
      file: >
        src={{ local_home }}/git/rusagedougawa/dotfiles/{{ item.src }}
        dest={{ local_home }}/{{ item.dest }}
        state=link
      with_items:
        - { src: '.zshenv', dest: '.zshenv' }
        - { src: '.vimrc', dest: '.vimrc' }

    - name: make vim.dein directory
      file: >
        dest={{ local_home }}/.vim/dein/repos/github.com/Shougo/dein.vim
        owner={{ ansible_env.USER }}
        state=directory
        recurse=yes

    - name: make directory
      file: >
        path={{ local_home }}/.config
        owner={{ ansible_env.USER }}
        state=directory

    - name: link dotfiles
      file: >
        src={{ local_home }}/{{ item.src }}
        dest={{ local_home }}/.config/{{ item.dest }}
        state=link
      with_items:
        - { src: '.vim', dest: 'nvim' }
        - { src: '.vimrc', dest: 'nvim/init.vim' }

    - name: install pyenv
      git: >
        repo=https://github.com/yyuu/pyenv.git
        dest=~/.pyenv

#      - name: add path
# export PYENV_ROOT=$HOME/.pyenv
# export PATH=$PYENV_ROOT/bin:$PATH
# eval "$(pyenv init -)"

# pyenv install 3.6.0
# pyenv global 3.6.0
# pip3 install ipython
